services:
  api:
    container_name: intuit_api
    build:
      context: ./api-service/
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: on-failure
    networks:
      - api_network
    volumes:
      - ./:/src

  # nginx:
  #   container_name: intuit_nginx
  #   build:
  #     context: ./nginx-service/
  #   restart: always
  #   # tty: true
  #   ports:
  #     - 80:80
  #   networks:
  #     - nginx_network
  #   depends_on:
  #      - api

networks:
  # nginx_network:
  #   driver: bridge
  api_network:
    driver: bridge
